# -*- coding: utf-8 -*-
"""Multi-Objective Portfolio Data Fetching.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14M6cVK7IWTmT3dhc3X0JOz_5eFS7Km39
"""

import numpy as np
import yfinance as yf
import pandas as pd
from sqlalchemy import create_engine
from google.colab import files

Hoy = pd.Timestamp.today()
Cuatro_Anios = pd.Timedelta(days = 365*4)
tickers = ["SPY","QQQ","BIMBOA.MX","WALMEX.MX","GLD","TLT","BTC-USD"]
tickers.sort()
datos = []
for ticker in tickers:
  datos_ticker = yf.download(ticker, start = Hoy - Cuatro_Anios, end = Hoy, auto_adjust = False).copy()
  if isinstance(datos_ticker.columns, pd.MultiIndex):
    datos_ticker.columns = datos_ticker.columns.get_level_values(0)
  datos_ticker = datos_ticker.reset_index()
  datos_ticker.rename(columns = {
      'Date': 'Fecha',
      'Adj Close': 'Precio_de_Cierre_Ajustado',
      'High': 'Precio_Maximo',
      'Low': 'Precio_Minimo',
      'Close': 'Precio_de_Cierre',
      'Open': 'Precio_de_Apertura',
      'Volume': 'Volumen'
      }, inplace = True)
  datos_ticker.insert(1,'Ticker',ticker)
  datos.append(datos_ticker)
activos_financieros = pd.concat(datos, ignore_index = True)
usd_to_mxn = yf.download('USDMXN=X', start = Hoy - Cuatro_Anios, end = Hoy, auto_adjust = False)['Close'].copy()
usd_to_mxn = usd_to_mxn.reset_index()
usd_to_mxn.rename(columns = {'Date': 'Fecha_Cambio', 'USDMXN=X': 'Precio_de_Cierre_Cambio'}, inplace = True)
conexion = create_engine('sqlite:///Activos Portafolio.db')
activos_financieros.to_sql('Activos_Financieros', conexion, if_exists = 'replace', index = False)
usd_to_mxn.to_sql('Tipo_de_Cambio_Dolar_a_Peso', conexion, if_exists = 'replace', index = False)
files.download('Activos Portafolio.db')